In [26]:
import numpy as np
A = np.arange(1, 16).reshape(3,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

Print out the dimension, shape, size and datatype of the matrix A

In [8]:
A.ndim

2

In [11]:
A.shape

(3, 5)

In [5]:
A.size

15

In [146]:
A.dtype

dtype('int32')

Skapa matris B och C och utför substration, multiplikation och matris multiplikation, standardsetting är elementwise för dessa grundläggande aritmetiska operationerna.

In [24]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2
print(B)
print()
print(C)
D = B - C
print()
print(D)
E = B * C
print()
print(E)
F = B @ C
print()
print(F)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


In [55]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exponentiate each number elementwise (use the np.exp function).

In [56]:
print(np.exp(B))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


Calculate the minimum value in the whole matrix.

In [57]:
print(B.min())

1


Calculcate the minimum value in each row.

In [63]:
print(B.min(axis=1))

[1 4 7]


Calculcate the minimum value in each column.

In [76]:
print(B.min(axis=0))

[1 2 3]


Find the index value for the minimum value in the whole matrix 

In [80]:
print(np.argmin(B))

0


Find the index value for the minimum value in each row

In [87]:
print(np.argmin(B, axis=1))

[0 0 0]


Calculate the sum for all elements.

In [77]:
print(B.sum())

45


Calculate the mean for each column.

In [73]:
print(np.mean(B,axis=0))

[4. 5. 6.]


Calculate the median for each column.

In [78]:
print(np.median(B, axis=0))

[4. 5. 6.]


What does it mean when you provide fewer indices than axes when slicing? 

In [88]:
A = np.arange(1, 16).reshape(3,5)
print(A)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [103]:
print(A[0])
print()
print(A[1])
print()
print(A[2])

[1 2 3 4 5]

[ 6  7  8  9 10]

[11 12 13 14 15]


Om man indexerar med enbart ett elment [X] tas samtliga elmement från matrisen A med på rad X, så att säga en : det index som inte angivits, istället att peka ut ett enskilt element på pos[x][y], får man då hela raden som output.

Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array elementwise, how would you do that?

In [105]:
A
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


Från NumPy quick start, hittas attibutet flat, initialt tänkte jag på den ineffektiva lösningen med dubbla for-loopar och indexering, men att platta ut matrisen är smidigare och jobba indirekt på size. Bra ide att matrisens form, kan i vissa situationer förändras, om position inte är viktigt.

In [8]:
import numpy as np
A = np.arange(1, 16).reshape(3,5)

for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


Explain what the code below does. More specifically, b has three axes - what does this mean?

In [25]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print(a.ndim)
print()
print(b)
b.ndim

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
1

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


3

I första steget skapas en a, en 1-D matris, som innehåller talen 30 tal, 0-29, med hjälp av attributet reshape läses matrix a, retureras i modiferad form, och ges namnet b, och är en 3-D matrix.

Remark on Broadcasting when doing Linear Algebra calculations in Python.
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy.

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

Vector- and matrix algebra Exercises
Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [163]:
import numpy as np
def add_multi_matrices(matrix1,matrix2,method):
    
    if isinstance(matrix1,np.ndarray) and isinstance(matrix2,np.ndarray):
        if method == "add":
            if matrix1.shape == matrix2.shape:
                return matrix1 + matrix2
            else:
                print("The matrices can't be added together due to being formatted incorrectly")
        elif method == "multiply":
            if matrix1.shape[1] == matrix2.shape[0]:
                return matrix1 @ matrix2
        else:
            print("The matrices can't be multiplied due to being in the wrong format, undefined")         
    else:   
        print("The matrices are of an invalid type, please correct the input")
add_multi_matrices(np.array([[1,2],[2,4]]),np.array([[1,4],[2,4]]),"add")                      

array([[2, 6],
       [4, 8]])

In [141]:
import numpy as np
x = np.array([[1,2],[2,4]])
type(x)


numpy.ndarray

Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan".

Uppgift 10.1.1
Defininera vektorn x = (4,3)

a) Vilken dimension har vektorn x?

In [22]:
import numpy as np
x=np.array([4,3])
x.ndim

1

b) Beräkna 5x

In [23]:
import numpy as np
print(5*x)

[20 15]


c) Beräkna 3x

In [24]:
import numpy as np
print(3*x)

[12  9]


d) Beräkna 5x + 3x = 8x

In [27]:
result = 5*x + 3*x
print(result)

[32 24]


e) Beräkna 8x, samma som ovan, och gav samma svar.

In [26]:
print(8*x)

[32 24]


f) Beräkna 4x - x = 3x

In [28]:
result = 4*x - 1*x
print(result)

[12  9]


g) Beräkna X${^T}$

In [31]:
x_trans=np.transpose(x)
print(x_trans)

[4 3]


h) Är X + X${^T}$ definerat ? Matriserna har olika storlek, en 1 x 2 och den andra är 2 x 1, dessa kan inte adderas, så inte definerat.

In [4]:
import numpy as np
x = np.array([[4,3]])
print(np.shape(x))
print()
x_trans = np.transpose(x)
print(np.shape(x_trans))

(1, 2)

(2, 1)


i) Beräkna ||x||

In [33]:
norm_x = np.linalg.norm(x)
print(norm_x)

5.0


Uppgift 10.1.2 Definiera vektorn v

In [35]:
v = np.array([[3],[7],[0],[11]])
print(v)

[[ 3]
 [ 7]
 [ 0]
 [11]]


a) vilken dimension har vektorn v?

In [36]:
v = np.array([[3],[7],[0],[11]])
v.ndim

2

b) Beräkna 2v

In [38]:
multi =2*v
print(multi)


[[ 6]
 [14]
 [ 0]
 [22]]


c) Beräkna 5v + 2v = 7v

In [39]:
multi =5 * v + 2 * v
print(multi)

[[21]
 [49]
 [ 0]
 [77]]


d) Beräkna 4v - 2v = 2v

In [40]:
multi =4 * v - 2 * v
print(multi)

[[ 6]
 [14]
 [ 0]
 [22]]


e) Beräkna v${^T}$

In [41]:
v_trans = v.transpose()
print(v_trans)
print()
v.ndim

[[ 3  7  0 11]]



2

f) Beräkna ||v||

In [42]:
v_norm = np.linalg.norm(v)
print(v_norm)

13.379088160259652


Uppgift 10.1.3 definera vektorna v1 och v2

In [44]:
import numpy as np
v1 = np.array([4,3,1,5])
v2 = np.array([2,3,1,1])

a) Beräkna ||v1||

In [45]:
v1_norm = np.linalg.norm(v1)
print(v1_norm)

7.14142842854285


In [ ]:
b) Beräkna || v1 - v2||

In [46]:
vectorcalc = v1 - v2

#Beräkningskontrollpunkt
print(vectorcalc)

big_norm = np.linalg.norm(vectorcalc)
print(big_norm)

[2 0 0 4]
4.47213595499958


Uppgift 10.2.1 Definiera matriserna A, B , C, D, E samt I

In [47]:
import numpy as np
A= np.array([[2,1,-1],[1,-1,1]])
B= np.array([[4,-2,1],[2,-4,-2]])
C= np.array([[1,2],[2,1]])
D= np.array([[3,4],[4,3]])
E= np.array([[1],[2]])
I= np.array([[1,0],[0,1]])

a) Beräkna 2A

In [6]:
A2= 2*A
print(A2)

[[ 4  2 -2]
 [ 2 -2  2]]


b) Beräkna B - 2A

In [48]:
calc= B - 2 * A
print(calc)

[[ 0 -4  3]
 [ 0 -2 -4]]


c) Beräkna 3C - 2E, Substraktion mellan matriserna är inte definerad eftersom C är en 2 x 2 matris och E är en 1 x 2) matris, och matematiskt kräver substraktionen att matriserna ska vara av samma storlek, avseende både rad och kolumn, uttrycket är ej definiterat.

In [49]:
print(C.shape)
print()
print(E.shape)

(2, 2)

(2, 1)


d) Beräkna 2D - 3C

In [50]:
calc= 2 * D - 3 * C
print(calc)

[[3 2]
 [2 3]]


e) Beräkna D${^T}$ + 2D

In [51]:
D_trans = np.transpose(D)
calc = D_trans + 2 * D
print(calc)

[[ 9 12]
 [12  9]]


f) Beräkna 2C${^T}$- 2D${^T}$

In [52]:
C_trans = np.transpose(C)
D_trans = np.transpose(D)
calc = 2 * C_trans -2 * D_trans
print(calc)

[[-4 -4]
 [-4 -4]]


g) Beräkna A${^T}$ - B  Subtraktionen av dessa matiser är inte möjligt eftersom A transposant är en 3x2 matris och B är en 2x3 matris, och vid addition och substraktion måste matriserna vara av samma shape.

In [53]:
A_trans = np.transpose(A)
print(A_trans.shape)
print()
print(B.shape)

(3, 2)

(2, 3)


h) Beräkna AC,  Matris is a 2 x 3 matrix, while C is a 2 x 2 matris, the number of coloums in the first matrix need be the same as the number of rows in the second matrix, so matrix multiplication of AC isn't defined.

In [54]:
print(A.shape)
print()
print(C.shape)

(2, 3)

(2, 2)


i) Beräkna CD

In [55]:
result = C @ D
print(result)

[[11 10]
 [10 11]]


j) Beräkna CB

In [56]:
result = C @ B
print(result)

[[  8 -10  -3]
 [ 10  -8   0]]


k) Beräkna CI

In [57]:
result = C @ I
print(result)

[[1 2]
 [2 1]]


l) Beräkna AB${^T}$

In [58]:
b_trans = np.transpose(B)
result = A @ b_trans
print(result)

[[5 2]
 [7 4]]


Uppgift 10.2.2 Definiera matrisen A, och beräkna AA${^T}$

In [59]:
A_trans= np.transpose(A)
result = A @ A_trans
print(result)

[[6 0]
 [0 3]]


Uppgift 10.2.3 Definiera matriserna A, B samt C 

In [6]:
import numpy as np
A = np.array([[1,2],[2,4]])
B = np.array([[2,1],[1,3]])
C = np.array([[4,3],[0,2]])
AB = A @ B
print(AB)
print()
AC = A @ C
print(AC)
print()
#The result from multiplication of AB is equal to the multiplication of AC
print(np.array_equal(AB,AC))
print()
print(B)
print()
print(C)
print()
# Matris B and C are not identical
print(np.array_equal(B,C))

[[ 4  7]
 [ 8 14]]

[[ 4  7]
 [ 8 14]]

True

[[2 1]
 [1 3]]

[[4 3]
 [0 2]]

False


Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [171]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [172]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)


None
[0 1 2 3]


Det kontrollerar man med hjälp av attibutet base, och i detta fallet är v1 är en copy, då den returnerer output "None", och v2 är view (eftersom den returnera vektorn som output.

In [173]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


Om man ändra sista elementet i v2 till 123, så kommer elementet även att ändras i v1, vilket man ser i koden ovan, både har samma element 123 sist i matrisen.

Copy är v1, är den nya vektorn och v2 är en en view av orginalvektorn, copy så att säga äger datan. Det gäller också ändringar i view påverkar både copy och view, illustreras ovan, och det är eftersom view inte äger datan utan ändringar där påverka båda två, sista elementet är 123 för både nu.